# Generated by Django 3.1 on 2020-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('firstname', models.CharField(blank=True, max_length=1000, null=True)),
                ('lastname', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
