# Generated by Django 3.1 on 2020-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('firstname', models.CharField(blank=True, max_length=1000, null=True)),
                ('lastname', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'userlist',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
